### ISSUE TITLE
DEV 온라인 정기 회의, 2023-10-10 [21:00]

### ISSUE THREAD

**Issue by wave-sound** [BRIDGE-DEV/DEV_Manage#2]
# DEV 온라인 정기 회의, 2023-10-10 [21:00]

- 회의 간격 관련 논의
- 멘토 모집 공고

## 회의 간격 관련 논의

- 현재로서 다룰 수 안건이 많지 않아 2주 간격으로 조정함.
- 추후 상황을 확인하고 간격에 대한 논의 다시 진행.

## 멘토, 멘티 모집 공고

- 브릿지 전체 카톡방에서 프로그래머들을 대상으로 모집글 작성
    - 멘토 :  Discussion 탭에서 브릿지 회원들의 질의에 답변을 해주는 선배 프로그래머를 의미함.

**Comment by fkdl0048** [comment]
@wave-sound 작성이랑 다음 스케줄 등록되면 close해주시면 됩니다!
