### ISSUE TITLE
DEV 온라인 정기 회의, 2023-10-31 [21:00]

### ISSUE THREAD

**Issue by wave-sound** [BRIDGE-DEV/DEV_Manage#3]
# DEV 온라인 정기 회의, 2023-10-31 [21:00]

- 회의 간격 관련 논의
- 운영진 방향성 논의

## 회의 간격 관련 논의

- 안건이 생각보다 잘 생기지 않아 비정기 회의로 전환
    - 안건이 발생할 때 마다 비정기적으로 회의 진행

## 데브 운영진 방향성 논의

- 스터디 개설 도움 및 브릿지 데브 참가에 대한 안내를 주된 업무로 지정.

**Comment by fkdl0048** [comment]
- 단톡 공지는 생각해보니 시험 이후에 작성하는게 좋을 것 같아서 미뤘습니다!
- ++ 새로 생긴 스터디 운영관련
